printf "
---
version: '3.8'

services:
  server:
    image: $REGISTRY_ADDR/$REPO_ORG/$REPO_GROUP/$REPO_NAME:${CI_COMMIT_SHA:0:8}
    networks:
      - $REPO_ORG-$REPO_GROUP-$REPO_NAME
    ports:
      - 5003:5003
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.stateless == true
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 10


networks:
  $REPO_ORG-$REPO_GROUP-$REPO_NAME:
    name: $REPO_ORG-$REPO_GROUP-$REPO_NAME
    driver: overlay
    attachable: true
"

